# Generated by Django 5.0.4 on 2024-04-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='user_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='user_identifier',
            field=models.CharField(max_length=36),
        ),
    ]
